# Generated by Django 3.1.3 on 2020-11-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_creator',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hours_played',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='map_plays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='success_rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
