# Generated by Django 3.1.3 on 2020-11-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201130_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='success_rate',
            new_name='successful_map_plays',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
