# Generated by Django 3.1.3 on 2020-11-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201130_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hours_played',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='successful_map_plays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
