# Generated by Django 3.1.3 on 2020-11-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_userprofile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hours_played',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='map_plays',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='successful_map_plays',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_score',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
