# Generated by Django 3.1.3 on 2020-11-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201130_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_creator',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hours_played',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='map_plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='successful_map_plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
