# Generated by Django 3.1.3 on 2020-12-01 08:00

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_userprofile_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='play_history',
            field=models.CharField(default='', max_length=99999, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
