# Generated by Django 3.1.3 on 2020-12-01 08:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20201201_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='play_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
    ]
