# Generated by Django 3.1.3 on 2020-12-01 08:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20201201_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='play_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], null=True, size=None),
        ),
    ]
