# Generated by Django 3.1.3 on 2020-12-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20201201_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='play_history',
        ),
    ]
